import { useState } from "react";
import companyLogo from "../imports/image.png";

const photo = "https://images.unsplash.com/photo-1614595737476-42487331b8a1?auto=format&fit=crop&w=1400&q=85";
const services = [
  { number: "01", title: "Tư vấn chiến lược", description: "Định hướng rõ ràng. Quyết định đúng đắn. Xây dựng nền tảng vững chắc cho tăng trưởng dài hạn.", detail: "Phân tích thị trường, xác định lợi thế cạnh tranh và xây dựng lộ trình tăng trưởng phù hợp với nguồn lực doanh nghiệp.", icon: "strategy" },
  { number: "02", title: "Chuyển đổi số", description: "Kết nối công nghệ với mục tiêu kinh doanh. Tối ưu vận hành, mở ra những cơ hội mới.", detail: "Đánh giá mức độ sẵn sàng, số hóa quy trình và triển khai hệ thống quản trị để đội ngũ làm việc hiệu quả hơn.", icon: "digital" },
  { number: "03", title: "Phát triển thương hiệu", description: "Tạo dựng bản sắc khác biệt. Kết nối đúng khách hàng. Biến thương hiệu thành lợi thế cạnh tranh.", detail: "Từ định vị và nhận diện đến trải nghiệm khách hàng, chúng tôi xây dựng thương hiệu nhất quán trên mọi điểm chạm.", icon: "brand" },
];
function Arrow({ diagonal = false, className = "" }: { diagonal?: boolean; className?: string }) {
  return <svg className={`h-5 w-5 ${className}`} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">{diagonal ? <path d="M6 18 18 6M6 6h12v12" /> : <path d="M4 12h15m-6-6 6 6-6 6" />}</svg>;
}
function Logo({ light = false }: { light?: boolean }) {
  return <a href="#" aria-label="HOÀNG HÀ DIGITAL — Trang chủ" className={`flex shrink-0 items-center justify-center overflow-hidden rounded-sm bg-white ${light ? "h-[110px] w-[110px]" : "h-[76px] w-[76px]"}`}><img src={companyLogo} alt="HOÀNG HÀ DIGITAL" className="h-full w-full object-contain" /></a>;
}
function ServiceIcon({ type }: { type: string }) {
  return <svg width="34" height="34" viewBox="0 0 36 36" fill="none" stroke="currentColor" strokeWidth="1.4" aria-hidden="true">{type === "strategy" ? <><path d="M6 29h24M9 24v-7h6v7m4 0V11h6v13M7 12l8-6 8 2 7-5" /><path d="M24 3h6v6" /></> : type === "digital" ? <><rect x="4" y="5" width="28" height="20" rx="2" /><path d="M12 31h12M18 25v6m-4-20-4 4 4 4m8-8 4 4-4 4" /></> : <><path d="m18 3 13 8v14l-13 8-13-8V11L18 3Z" /><path d="m5 11 13 8 13-8M18 19v14m-7-26 14 9" /></>}</svg>;
}
export default function App() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [contactOpen, setContactOpen] = useState(false);
  const [submitted, setSubmitted] = useState(false);
  const [selected, setSelected] = useState<number | null>(null);
  const nav = [["Về chúng tôi", "about"], ["Giải pháp", "services"], ["Vì sao chọn HOÀNG HÀ DIGITAL", "why"]];
  const contact = () => { setSubmitted(false); setContactOpen(true); setMenuOpen(false); };
  return <div className="overflow-x-clip">
    <header className="relative z-20 border-b border-border bg-background">
      <div className="mx-auto flex h-[88px] max-w-[1280px] items-center justify-between px-6 lg:px-10">
        <Logo />
        <nav className="hidden items-center gap-10 text-[13px] font-medium md:flex" aria-label="Điều hướng chính">{nav.map(([label, id]) => <a key={id} href={`#${id}`} className="transition-colors hover:text-[#bc6240]">{label}</a>)}</nav>
        <button onClick={contact} className="hidden items-center gap-7 rounded-full bg-[#183d38] px-6 py-3.5 text-[13px] text-white transition-colors hover:bg-[#2d5950] md:flex">Liên hệ với chúng tôi <Arrow diagonal /></button>
        <button className="flex h-10 w-10 flex-col items-center justify-center gap-1.5 md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Đóng menu" : "Mở menu"} aria-expanded={menuOpen}><span className={`h-px w-6 bg-current transition-transform ${menuOpen ? "translate-y-1 rotate-45" : ""}`} /><span className={`h-px w-6 bg-current transition-transform ${menuOpen ? "-translate-y-1 -rotate-45" : ""}`} /></button>
      </div>
      {menuOpen && <nav className="absolute inset-x-0 top-full flex flex-col gap-5 border-b border-border bg-background px-6 py-7 shadow-lg md:hidden">{nav.map(([label, id]) => <a href={`#${id}`} key={id} onClick={() => setMenuOpen(false)}>{label}</a>)}<button onClick={contact} className="text-left font-semibold text-[#bc6240]">Liên hệ với chúng tôi ↗</button></nav>}
    </header>
    <main>
      <section className="mx-auto max-w-[1280px] px-6 pb-12 pt-11 md:pb-16 md:pt-[68px] lg:px-10">
        <div className="grid items-center gap-10 md:grid-cols-[1.1fr_1fr] md:gap-12">
          <div className="pb-2">
            <div className="mb-6 flex items-center gap-2.5 text-[10px] font-semibold tracking-[2px] md:mb-7"><span className="h-2 w-2 rounded-full bg-[#bb6749]" /> ĐỐI TÁC CHO SỰ TĂNG TRƯỞNG</div>
            <h1 className="text-[43px] font-medium leading-[1.23] tracking-[-1.6px] lg:text-[63px] lg:leading-[1.17]">Cùng bạn kiến tạo<br className="hidden lg:block" /> <span className="text-[#b96546]">giá trị bền vững.</span></h1>
            <p className="mt-6 max-w-[440px] text-[14px] leading-[1.9] text-[#728079] md:mt-7 md:text-[15px]">Từ chiến lược đến thực thi, HOÀNG HÀ DIGITAL đồng hành cùng doanh nghiệp khai mở tiềm năng, tạo nên những bước tiến khác biệt.</p>
            <div className="mt-8 flex flex-wrap items-center gap-6 md:mt-9"><a href="#services" className="flex items-center gap-6 rounded-full bg-[#183d38] px-6 py-4 text-xs font-medium text-white transition-colors hover:bg-[#2d5950]">Khám phá giải pháp <Arrow diagonal /></a><button onClick={contact} className="flex items-center gap-2 text-xs font-medium">Kết nối với HOÀNG HÀ DIGITAL <Arrow /></button></div>
            <div className="mt-10 flex items-center gap-3 border-t border-border pt-5 md:mt-12"><div className="flex -space-x-2" aria-hidden="true">{["L", "M", "H", "A"].map((name, index) => <span key={name} className={`flex h-8 w-8 items-center justify-center rounded-full border-2 border-background text-[10px] font-medium ${["bg-[#dbd5bd]", "bg-[#b9c9bd]", "bg-[#d6bba6]", "bg-[#9daea1]"][index]}`}>{name}</span>)}</div><p className="text-[10px] leading-5 text-[#758077]"><strong className="font-semibold text-foreground">Hơn 200 doanh nghiệp</strong><br />đã chọn HOÀNG HÀ DIGITAL để cùng phát triển</p></div>
          </div>
          <div className="relative pb-5 md:pb-7">
            <div className="relative h-[370px] overflow-hidden rounded-[3px] md:h-[470px] lg:h-[502px]"><img src={photo} alt="Kiến trúc hiện đại hướng lên bầu trời — biểu tượng của sự phát triển" className="h-full w-full object-cover object-[50%_47%]" /><div className="absolute inset-0 bg-[#183d38]/10" /><div className="absolute left-6 top-6 flex items-center gap-2 rounded-full border border-white/40 bg-white/10 px-3 py-2 text-[9px] tracking-[1.5px] text-white backdrop-blur-sm"><span className="h-1.5 w-1.5 rounded-full bg-white" /> BUILDING WHAT'S NEXT</div><div className="absolute bottom-8 right-7 text-[85px] font-light leading-none text-white/80">↗</div></div>
            <div className="absolute -bottom-0 left-5 flex items-center gap-5 rounded-sm bg-[#e5eadc] px-6 py-5 shadow-[0_8px_24px_#183d3810] md:-left-7"><span className="text-4xl font-medium tracking-[-1px]">10<span className="text-[#b96546]">+</span></span><span className="text-[11px] leading-5">Năm kinh nghiệm<br />Tạo giá trị thực, bền vững</span></div>
          </div>
        </div>
      </section>
      <section className="border-y border-border bg-[#f0f2eb]">
        <div className="mx-auto max-w-[1280px] px-6 py-8 lg:px-10"><p className="mb-7 text-center text-[10px] font-medium tracking-[1.5px] text-[#748077]">ĐỒNG HÀNH CÙNG NHỮNG DOANH NGHIỆP TIÊN PHONG</p><div className="grid grid-cols-3 items-center gap-x-6 gap-y-7 text-center text-[#78857b] md:grid-cols-6"><span className="text-xl font-bold italic tracking-[-1px]">FPT<span className="text-xs not-italic"> Software</span></span><span className="text-xl font-bold tracking-[-1px]">vinamilk</span><span className="text-lg font-semibold">momo</span><span className="text-lg font-semibold italic">Viettel</span><span className="text-lg font-bold tracking-[-1px]">VNG<span className="ml-0.5 text-xs">◢</span></span><span className="text-[15px] font-bold">Techcombank <span className="text-sm">◆</span></span></div></div>
      </section>
      <section id="about" className="mx-auto grid max-w-[1280px] gap-7 px-6 py-16 md:grid-cols-[.85fr_1.15fr] md:gap-20 md:py-24 lg:px-10"><div><p className="mb-5 text-[10px] font-semibold tracking-[2px] text-[#a96045]">01 / VỀ HOÀNG HÀ DIGITAL</p><h2 className="text-[31px] font-medium leading-[1.4] md:text-[38px]">Không chỉ là giải pháp.<br />Là một sự đồng hành.</h2></div><div><p className="text-[14px] leading-[1.95] text-[#6e7b73]">Chúng tôi tin rằng mỗi doanh nghiệp đều có tiềm năng tạo nên điều lớn lao. HOÀNG HÀ DIGITAL kết hợp tư duy chiến lược, công nghệ và sự thấu hiểu để biến tiềm năng đó thành giá trị thực tế.</p><p className="mt-4 text-[14px] leading-[1.95] text-[#6e7b73]">Không có công thức chung cho thành công. Chúng tôi lắng nghe câu chuyện của bạn, thiết kế giải pháp riêng và đồng hành trên từng bước phát triển.</p><a href="#why" className="mt-6 inline-flex items-center gap-8 border-b border-[#a8b3a7] pb-2 text-xs font-medium">Điều làm nên HOÀNG HÀ DIGITAL <Arrow diagonal /></a></div></section>
      <section id="services" className="bg-[#eaf0e5] py-16 md:py-20"><div className="mx-auto max-w-[1280px] px-6 lg:px-10"><div className="mb-9 flex flex-col justify-between gap-5 md:mb-11 md:flex-row md:items-end"><div><p className="mb-4 text-[10px] font-semibold tracking-[2px] text-[#a96045]">02 / GIẢI PHÁP CỦA CHÚNG TÔI</p><h2 className="text-[31px] font-medium leading-[1.4] md:text-[38px]">Một tầm nhìn.<br />Nhiều cách tạo giá trị.</h2></div><p className="max-w-[320px] text-[13px] leading-6 text-[#738070]">Giải pháp toàn diện, được thiết kế để giải quyết đúng thách thức của doanh nghiệp bạn.</p></div><div className="grid gap-4 md:grid-cols-3">{services.map((service, index) => <article key={service.number} className={`group flex flex-col rounded-sm border p-7 transition-colors lg:p-8 ${index === 0 ? "border-[#183d38] bg-[#183d38] text-white" : "border-[#d9e1d2] bg-[#f8faf4] text-foreground"}`}><div className="mb-10 flex items-center justify-between"><ServiceIcon type={service.icon} /><span className={`text-[11px] ${index === 0 ? "text-white/40" : "text-[#8a9687]"}`}>{service.number}</span></div><h3 className="mb-4 text-[20px] font-medium">{service.title}</h3><p className={`min-h-[90px] text-[12px] leading-[1.9] ${index === 0 ? "text-white/65" : "text-[#778271]"}`}>{service.description}</p>{selected === index && <p className="mb-4 text-xs leading-6">{service.detail}</p>}<button onClick={() => setSelected(selected === index ? null : index)} aria-expanded={selected === index} className={`mt-auto flex w-full items-center justify-between border-t pt-5 text-[11px] font-medium ${index === 0 ? "border-white/20" : "border-[#dce2d5]"}`}>{selected === index ? "Thu gọn" : "Tìm hiểu giải pháp"}<Arrow diagonal /></button></article>)}</div></div></section>
      <section id="why" className="mx-auto max-w-[1280px] px-6 py-16 md:py-24 lg:px-10"><div className="grid gap-10 md:grid-cols-[1fr_1.2fr] md:gap-24"><div><p className="mb-5 text-[10px] font-semibold tracking-[2px] text-[#a96045]">03 / VÌ SAO CHỌN HOÀNG HÀ DIGITAL</p><h2 className="text-[31px] font-medium leading-[1.4] md:text-[38px]">Thấu hiểu sâu.<br />Hành động thực.<br /><span className="text-[#b96546]">Kết quả khác biệt.</span></h2><p className="mt-6 max-w-[300px] text-[13px] leading-7 text-[#738070]">Thành công của bạn không chỉ là mục tiêu. Đó là thước đo cho mọi điều chúng tôi làm.</p></div><div>{[["01", "Chiến lược gắn liền với thực tiễn", "Không dừng lại ở những bản kế hoạch. Chúng tôi biến ý tưởng thành hành động và kết quả đo lường được."], ["02", "Đội ngũ đa chuyên môn", "Chuyên gia chiến lược, công nghệ và sáng tạo cùng phối hợp, mang đến góc nhìn toàn diện cho mỗi thách thức."], ["03", "Đồng hành, không chỉ cung cấp", "Lắng nghe, linh hoạt và cam kết dài hạn. Chúng tôi phát triển cùng doanh nghiệp, trên mỗi chặng đường."]].map(([number, title, text]) => <div key={number} className="flex gap-5 border-b border-border py-6 first:pt-0 last:border-0"><span className="mt-1 text-[11px] text-[#b96546]">{number}</span><div><h3 className="mb-3 text-[16px] font-medium">{title}</h3><p className="text-[12px] leading-6 text-[#778271]">{text}</p></div></div>)}</div></div><div className="mt-12 grid grid-cols-2 gap-y-8 border-t border-border pt-9 md:mt-16 md:grid-cols-4">{[["10+", "Năm kinh nghiệm"], ["200+", "Doanh nghiệp đồng hành"], ["350+", "Dự án triển khai"], ["98%", "Khách hàng hài lòng"]].map(([value, label]) => <div key={value} className="text-center md:border-r md:border-border md:last:border-0"><p className="text-[36px] font-medium tracking-[-1px] md:text-[43px]">{value}</p><p className="mt-2 text-[10px] text-[#7b8575]">{label}</p></div>)}</div></section>
      <section className="bg-[#dfe7d6]"><div className="mx-auto flex max-w-[1280px] flex-col items-start justify-between gap-7 px-6 py-12 md:flex-row md:items-center md:py-16 lg:px-10"><div><p className="mb-4 text-[10px] font-semibold tracking-[2px] text-[#6d7b62]">CÙNG BẮT ĐẦU MỘT ĐIỀU LỚN LAO</p><h2 className="text-[28px] font-medium leading-[1.4] md:text-[36px]">Bước tiến tiếp theo của bạn,<br />bắt đầu từ một cuộc trò chuyện.</h2></div><button onClick={contact} className="flex items-center gap-8 rounded-full bg-[#183d38] px-7 py-4 text-xs text-white hover:bg-[#2d5950]">Trao đổi cùng chuyên gia <Arrow diagonal /></button></div></section>
    </main>
    <footer className="bg-[#183d38] text-white"><div className="mx-auto max-w-[1280px] px-6 pt-12 lg:px-10"><div className="grid gap-10 pb-12 md:grid-cols-[1.4fr_1fr_1fr_1.2fr]"><div><Logo light /><p className="mt-5 max-w-[230px] text-[11px] leading-6 text-white/50">Kiến tạo giá trị.<br />Đồng hành cùng tăng trưởng.</p></div><div><h3 className="mb-5 text-xs font-medium">Khám phá HOÀNG HÀ DIGITAL</h3><div className="flex flex-col gap-3 text-[11px] text-white/55">{nav.map(([label, id]) => <a key={id} href={`#${id}`} className="hover:text-white">{label}</a>)}</div></div><div><h3 className="mb-5 text-xs font-medium">Giải pháp</h3><div className="flex flex-col gap-3 text-[11px] text-white/55">{services.map((service, index) => <a href="#services" key={service.title} onClick={() => setSelected(index)} className="hover:text-white">{service.title}</a>)}</div></div><div><h3 className="mb-5 text-xs font-medium">Kết nối với chúng tôi</h3><button onClick={contact} className="text-[13px]">Liên hệ tư vấn ↗</button><p className="mt-3 text-[11px] leading-6 text-white/55">Hoàng Mai, Hà Nội</p><button onClick={contact} className="mt-4 border-b border-white/35 pb-1 text-[11px]">Đặt lịch tư vấn ↗</button></div></div><div className="flex flex-col justify-between gap-3 border-t border-white/15 py-5 text-[9px] text-white/40 sm:flex-row"><p>© {new Date().getFullYear()} HOÀNG HÀ DIGITAL. Bảo lưu mọi quyền.</p><p>Thiết kế cho hôm nay. Phát triển cho ngày mai.</p></div></div></footer>
    {contactOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#102f2a]/60 p-5 backdrop-blur-sm" onClick={() => setContactOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="contact-title" className="relative max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-lg bg-background p-7 md:p-10" onClick={event => event.stopPropagation()} onKeyDown={event => { if (event.key === "Escape") setContactOpen(false); }}><button autoFocus onClick={() => setContactOpen(false)} aria-label="Đóng" className="absolute right-5 top-4 text-2xl">×</button><p className="mb-4 text-[10px] tracking-[2px] text-[#a96045]">BẮT ĐẦU KẾT NỐI</p><h2 id="contact-title" className="mb-5 text-2xl font-medium">Cùng tạo nên bước tiến mới.</h2>{submitted ? <div role="status"><p className="text-sm leading-7">Thông tin của bạn đã sẵn sàng trong ứng dụng email. Vui lòng điền địa chỉ email của HOÀNG HÀ DIGITAL vào mục người nhận trước khi gửi.</p><button onClick={() => setContactOpen(false)} className="mt-6 rounded-full bg-[#183d38] px-6 py-3 text-xs text-white">Hoàn tất</button></div> : <form onSubmit={event => { event.preventDefault(); const data = new FormData(event.currentTarget); const body = `Họ tên: ${data.get("name")}\nEmail: ${data.get("email")}\nNhu cầu: ${data.get("message")}`; window.location.href = `mailto:?subject=${encodeURIComponent("Yêu cầu tư vấn HOÀNG HÀ DIGITAL")}&body=${encodeURIComponent(body)}`; setSubmitted(true); }} className="flex flex-col gap-4"><label className="text-xs">Họ và tên<input required name="name" autoComplete="name" className="mt-2 block w-full rounded border border-border bg-white p-3 outline-none focus:border-[#183d38]" placeholder="Nguyễn Minh Anh" /></label><label className="text-xs">Email doanh nghiệp<input required name="email" type="email" autoComplete="email" className="mt-2 block w-full rounded border border-border bg-white p-3 outline-none focus:border-[#183d38]" placeholder="ban@doanhnghiep.vn" /></label><label className="text-xs">Bạn đang tìm kiếm giải pháp gì?<textarea required name="message" rows={3} className="mt-2 block w-full resize-y rounded border border-border bg-white p-3 outline-none focus:border-[#183d38]" placeholder="Chia sẻ một chút về mục tiêu của bạn…" /></label><button type="submit" className="mt-2 flex items-center justify-between rounded-full bg-[#183d38] px-6 py-4 text-xs text-white">Gửi yêu cầu qua email <Arrow diagonal /></button><p className="text-[10px] leading-5 text-[#738070]">Biểu mẫu sẽ mở ứng dụng email. Vui lòng bổ sung email người nhận; thông tin chỉ được gửi khi bạn xác nhận.</p></form>}</section></div>}
  </div>;
}
